-- HISTORICAL / SUPERSEDED — do not run.
--
-- This file used to define the "hosted_bots" Supabase-JS bot-hosting system
-- (hosted_bots, bot_members, bot_wallet_tx, bot_ads, bot_appointments,
-- bot_ad_views, store_products, marketplace_listings, locations,
-- medical_facilities, facility_shifts/bookings, ad_tasks/completions,
-- platform_ledger, bot_owner_withdrawals, platform_ads) plus a "hosted-bot-
-- builder" purchasable service and a bulk services.is_active=false update.
--
-- All of that is now dead or actively wrong if re-run:
-- - The hosted_bots system was deleted and replaced by the current Prisma
--   `Bot` model (prisma/schema.prisma) + src/app/bots/**, src/app/api/bots/**
--   (docs/AGENT_BUS.md, docs/agent-outbox.md: "permanently gone ... nothing
--   to restore"). No code anywhere queries hosted_bots/bot_members/etc.
-- - The "hosted-bot-builder" service insert below used `on conflict (slug)
--   do nothing`, which only prevents a duplicate INSERT — it does NOT
--   prevent resurrecting a row that was since hard-DELETEd. That service
--   was found broken (told buyers to redeem their order code on /bots, but
--   /bots/deploy never reads the orders table at all — see
--   migration_remove_locked_code_products.sql) and was later hard-deleted
--   for good (migration_final_cleanup_2026_09_09.sql). Re-running this file
--   would silently bring the broken, deleted $15 service back.
-- - The bulk `update services set is_active = false where slug in (...)`
--   below included 'faq-bot' and 'auto-reply-bot' — both free, live tools
--   linked from /free-tools. migration_remove_locked_code_products.sql had
--   to reactivate them after this exact statement broke them once already.
--   Re-running this file would break them again.
--
-- Kept only for git history/context. See migration_remove_locked_code_products.sql
-- and migration_final_cleanup_2026_09_09.sql for the corrected, current state.
