import type { Metadata } from "next";
import { SITE, PATH } from "./botsPageCopy";

export const botsMetadata: Metadata = {
  title: "تفعيل بوت تليجرام — سوق تولز",
  description:
    "فعّل بوت تليجرام يعمل فعلياً على توكنك الخاص خلال دقائق: مشاهدة إعلانات وربح نقاط، محفظة، وإحالة. منتج جاهز تملكه وتشغّله فوراً — بدون كتابة أي شيء.",
  keywords: [
    "بوت تليجرام",
    "تفعيل بوت تليجرام",
    "بوت مستضاف",
    "سوق تولز",
    "توكن BotFather",
    "بعد تفعيل البوت",
    "إعادة توليد التوكن",
    "اسم مستخدم البوت",
    "ويبهوك البوت",
    "setWebhook",
    "getUpdates",
    "تعارض الويبهوك",
    "حذف البوت من BotFather",
    "استرجاع توكن البوت",
    "إضافة البوت لمجموعة",
    "setprivacy",
    "setjoingroups",
    "مشرف قناة",
    "رفع البوت مشرفا",
    "قناة تليجرام",
    "channel admin bot",
    "حد رسائل تليجرام",
    "flood",
    "أوامر البوت",
    "setcommands",
    "قائمة الأوامر",
    "بدء المحادثة",
    "/start",
    "مراسلة بدون ستارت",
    "تغيير يوزر البوت",
    "اسم مستخدم BotFather",
    "/setusername",
    "اسم البوت الظاهر",
    "وصف البوت",
    "setname",
    "setdescription",
    "setabouttext",
    "حد ملفات تليجرام",
    "حجم الملف",
    "Bot API file size",
    "حظر البوت",
    "block bot",
    "فك حظر البوت",
    "وضع الإنلاين",
    "inline mode",
    "setinline",
    "صورة البوت",
    "setuserpic",
    "صورة ملف البوت",
    "توكن واحد ويبهوك واحد",
    "نفس التوكن على موقعين",
    "منصة بوت أخرى",
    "ويبهوك HTTPS",
    "webhook http",
    "شهادة SSL الويبهوك",
    "مدفوعات تليجرام",
    "Telegram Payments",
    "setpayments",
    "فواتير البوت",
    "setdomain",
    "Telegram Login",
    "ويدجت تسجيل تليجرام",
    "نطاق بوت تليجرام",
    "نقل ملكية البوت",
    "mybots",
    "مدير بوت مشارك",
    "نقل ملكية BotFather",
    "Mini App",
    "web_app",
    "setmenubutton",
    "زر قائمة البوت",
    "تطبيق مصغر تليجرام",
    "Telegram Business",
    "حساب أعمال تليجرام",
    "ربط البوت بحساب أعمال",
    "نجوم تليجرام",
    "Telegram Stars",
    "XTR",
    "فواتير نجوم",
    "قصص تليجرام",
    "Telegram Stories",
    "نشر قصة بوت",
    "bot stories",
    "ألعاب تليجرام",
    "Telegram Games",
    "sendGame",
    "setGameScore",
    "لعبة بوت تليجرام",
    "هدايا تليجرام",
    "Telegram Gifts",
    "إرسال هدية بوت",
    "bot gifts",
    "حزم ملصقات",
    "Sticker Set",
    "custom emoji",
    "newstickers",
    "إيموجي مخصص",
    "Telegram Passport",
    "جواز تليجرام",
    "بيانات جواز البوت",
    "مستندات هوية تليجرام",
    "مواضيع منتدى",
    "Forum topics",
    "createForumTopic",
    "message_thread_id",
    "منتدى مجموعة تليجرام",
    "تعزيز دردشة",
    "Chat Boost",
    "Premium boost",
    "boost channel",
    "تعزيز قناة تليجرام",
    "تفاعلات الرسائل",
    "Message reactions",
    "setMessageReaction",
    "تفاعل رسالة تليجرام",
    "حملة تفاعلات تليجرام",
    "وسائط مدفوعة",
    "Paid Media",
    "sendPaidMedia",
    "محتوى مدفوع تليجرام",
    "وسائط مدفوعة بوت",
    "مكالمات مجموعة تليجرام",
    "Voice Chat",
    "Video Chat",
    "Group call",
    "createVideoChat",
    "مكالمة صوت مجموعة",
    "سحوبات تليجرام",
    "Giveaways",
    "Premium giveaway",
    "giveaway",
    "سحب بريميوم تليجرام",
    "قائمة مهام تليجرام",
    "Checklist",
    "todo list",
    "sendChecklist",
    "قائمة مهام بوت",
    "استطلاع تليجرام",
    "تصويت تليجرام",
    "Poll",
    "Quiz",
    "sendPoll",
    "استبيان بوت",
    "نرد تليجرام",
    "Dice",
    "sendDice",
    "animated emoji",
    "إيموجي متحرك بوت",
    "موقع تليجرام",
    "Location",
    "live location",
    "sendLocation",
    "sendVenue",
    "موقع حي بوت",
    "جهة اتصال تليجرام",
    "Contact",
    "sendContact",
    "vCard",
    "بطاقة تعريف بوت",
    "رابط دعوة تليجرام",
    "Invite link",
    "createChatInviteLink",
    "exportChatInviteLink",
    "revokeChatInviteLink",
    "رابط دعوة مجموعة",
    "تثبيت رسالة تليجرام",
    "Pin message",
    "pinChatMessage",
    "unpinChatMessage",
    "unpinAllChatMessages",
    "إلغاء تثبيت رسالة بوت",
    "ترقية مشرف تليجرام",
    "Promote chat member",
    "promoteChatMember",
    "setChatAdministratorCustomTitle",
    "setChatPermissions",
    "صلاحيات المجموعة",
    "لقب مشرف مخصص",
    "تعديل رسالة تليجرام",
    "حذف رسالة تليجرام",
    "Edit message",
    "delete message",
    "editMessageText",
    "deleteMessage",
    "editMessageCaption",
    "إعادة توجيه رسالة تليجرام",
    "نسخ رسالة تليجرام",
    "Forward message",
    "copy message",
    "forwardMessage",
    "copyMessage",
    "forwardMessages",
    "إرسال صورة تليجرام",
    "إرسال فيديو تليجرام",
    "sendPhoto",
    "sendVideo",
    "sendDocument",
    "sendAudio",
    "sendMediaGroup",
    "مجموعة وسائط بوت",
    "رسالة صوتية تليجرام",
    "sendVoice",
    "sendVideoNote",
    "sendAnimation",
    "ملاحظة مرئية بوت",
    "إرسال ملصق تليجرام",
    "sendSticker",
    "getStickerSet",
    "حالة الكتابة تليجرام",
    "sendChatAction",
    "typing indicator",
    "upload_photo",
    "record_voice",
    "ReplyKeyboard",
    "InlineKeyboard",
    "answerCallbackQuery",
    "لوحة أزرار تليجرام",
    "زر إنلاين",
    "answerInlineQuery",
    "inline query",
    "chosen_inline_result",
    "نتائج البحث الإنلاين",
    "بحث إنلاين بوت",
    "getChat",
    "getChatMember",
    "getChatAdministrators",
    "getChatMemberCount",
    "عدد أعضاء المجموعة",
    "قائمة مشرفين تليجرام",
    "حالة عضو المجموعة",
    "معلومات المجموعة تليجرام",
    "getMe",
    "getWebhookInfo",
    "logOut",
    "close",
    "هوية البوت",
    "معلومات الويبهوك",
    "إيقاف جلسة البوت",
    "إغلاق التوكن تليجرام",
  ],
  alternates: { canonical: `${SITE}${PATH}` },
  openGraph: {
    title: "تفعيل بوت تليجرام — سوق تولز",
    description:
      "بوت يعمل على توكنك. طلب واحد = بوت واحد. لا سحب نقدي ولا كود للتحميل.",
    url: `${SITE}${PATH}`,
    locale: "ar_AR",
    type: "website",
    images: [{ url: `${SITE}/og/cover.jpg`, width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "تفعيل بوت تليجرام — سوق تولز",
    description: "منتج جاهز على توكنك. طلب واحد = بوت واحد. لا سحب نقدي.",
    images: [`${SITE}/og/cover.jpg`],
  },
};
