import type { Metadata } from "next";
import { SITE, PATH } from "./botsPageCopy";

export const botsMetadata: Metadata = {
  title: "تفعيل بوت تليجرام — سوق تولز",
  description:
    "فعّل بوت تليجرام يعمل فعلياً على توكنك الخاص خلال دقائق: مشاهدة إعلانات وربح نقاط، محفظة، وإحالة. منتج جاهز تملكه وتشغّله فوراً — بدون كتابة أي شيء.",
  keywords: [
    "بوت تليجرام",
    "تفعيل بوت تليجرام",
    "بوت مستضاف",
    "سوق تولز",
    "توكن BotFather",
    "بعد تفعيل البوت",
    "إعادة توليد التوكن",
    "اسم مستخدم البوت",
    "ويبهوك البوت",
    "setWebhook",
    "getUpdates",
    "تعارض الويبهوك",
    "حذف البوت من BotFather",
    "استرجاع توكن البوت",
    "إضافة البوت لمجموعة",
    "setprivacy",
    "setjoingroups",
    "مشرف قناة",
    "رفع البوت مشرفا",
    "قناة تليجرام",
    "channel admin bot",
    "حد رسائل تليجرام",
    "flood",
    "أوامر البوت",
    "setcommands",
    "قائمة الأوامر",
    "بدء المحادثة",
    "/start",
    "مراسلة بدون ستارت",
    "تغيير يوزر البوت",
    "اسم مستخدم BotFather",
    "/setusername",
    "اسم البوت الظاهر",
    "وصف البوت",
    "setname",
    "setdescription",
    "setabouttext",
    "حد ملفات تليجرام",
    "حجم الملف",
    "Bot API file size",
    "حظر البوت",
    "block bot",
    "فك حظر البوت",
    "وضع الإنلاين",
    "inline mode",
    "setinline",
    "صورة البوت",
    "setuserpic",
    "صورة ملف البوت",
    "توكن واحد ويبهوك واحد",
    "نفس التوكن على موقعين",
    "منصة بوت أخرى",
    "ويبهوك HTTPS",
    "webhook http",
    "شهادة SSL الويبهوك",
    "مدفوعات تليجرام",
    "Telegram Payments",
    "setpayments",
    "فواتير البوت",
    "setdomain",
    "Telegram Login",
    "ويدجت تسجيل تليجرام",
    "نطاق بوت تليجرام",
    "نقل ملكية البوت",
    "mybots",
    "مدير بوت مشارك",
    "نقل ملكية BotFather",
    "Mini App",
    "web_app",
    "setmenubutton",
    "زر قائمة البوت",
    "تطبيق مصغر تليجرام",
    "Telegram Business",
    "حساب أعمال تليجرام",
    "ربط البوت بحساب أعمال",
    "نجوم تليجرام",
    "Telegram Stars",
    "XTR",
    "فواتير نجوم",
    "قصص تليجرام",
    "Telegram Stories",
    "نشر قصة بوت",
    "bot stories",
    "ألعاب تليجرام",
    "Telegram Games",
    "sendGame",
    "setGameScore",
    "لعبة بوت تليجرام",
    "هدايا تليجرام",
    "Telegram Gifts",
    "إرسال هدية بوت",
    "bot gifts",
    "حزم ملصقات",
    "Sticker Set",
    "custom emoji",
    "newstickers",
    "إيموجي مخصص",
    "Telegram Passport",
    "جواز تليجرام",
    "بيانات جواز البوت",
    "مستندات هوية تليجرام",
    "مواضيع منتدى",
    "Forum topics",
    "createForumTopic",
    "message_thread_id",
    "منتدى مجموعة تليجرام",
    "تعزيز دردشة",
    "Chat Boost",
    "Premium boost",
    "boost channel",
    "تعزيز قناة تليجرام",
    "تفاعلات الرسائل",
    "Message reactions",
    "setMessageReaction",
    "تفاعل رسالة تليجرام",
    "حملة تفاعلات تليجرام",
    "وسائط مدفوعة",
    "Paid Media",
    "sendPaidMedia",
    "محتوى مدفوع تليجرام",
    "وسائط مدفوعة بوت",
    "مكالمات مجموعة تليجرام",
    "Voice Chat",
    "Video Chat",
    "Group call",
    "createVideoChat",
    "مكالمة صوت مجموعة",
  ],
  alternates: { canonical: `${SITE}${PATH}` },
  openGraph: {
    title: "تفعيل بوت تليجرام — سوق تولز",
    description:
      "بوت يعمل على توكنك. طلب واحد = بوت واحد. لا سحب نقدي ولا كود للتحميل.",
    url: `${SITE}${PATH}`,
    locale: "ar_AR",
    type: "website",
    images: [{ url: `${SITE}/og/cover.jpg`, width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "تفعيل بوت تليجرام — سوق تولز",
    description: "منتج جاهز على توكنك. طلب واحد = بوت واحد. لا سحب نقدي.",
    images: [`${SITE}/og/cover.jpg`],
  },
};
