import type { Metadata } from "next";
import { SITE, PATH } from "./botsPageCopy";

export const botsMetadata: Metadata = {
  title: "تفعيل بوت تليجرام — سوق تولز",
  description:
    "فعّل بوت تليجرام يعمل على توكنك. طلب واحد = بوت واحد. لا سحب نقدي ولا كود للتحميل.",
  keywords: [
    "بوت تليجرام",
    "تفعيل بوت تليجرام",
    "بوت مستضاف",
    "سوق تولز",
    "توكن BotFather",
    "setChatTitle",
    "setChatDescription",
    "setChatPhoto",
    "deleteChatPhoto",
    "leaveChat",
    "pinChatMessage",
    "unpinChatMessage",
    "unpinAllChatMessages",
    "تثبيت رسالة تليجرام",
    "فك تثبيت المجموعة",
    "exportChatInviteLink",
    "createChatInviteLink",
    "editChatInviteLink",
    "revokeChatInviteLink",
    "رابط دعوة تليجرام",
    "إلغاء رابط دعوة",
    "banChatMember",
    "unbanChatMember",
    "restrictChatMember",
    "promoteChatMember",
    "حظر عضو تليجرام",
    "رفع حظر المجموعة",
    "تقييد صلاحيات عضو",
    "setChatPermissions",
    "approveChatJoinRequest",
    "declineChatJoinRequest",
    "صلاحيات المجموعة",
    "طلب انضمام تليجرام",
    "getChatAdministrators",
    "getChatMember",
    "getChatMemberCount",
    "getChat",
    "قائمة مشرفين المجموعة",
    "عدد أعضاء تليجرام",
    "setMyCommands",
    "deleteMyCommands",
    "getMyCommands",
    "setMyName",
    "قائمة أوامر البوت",
    "اسم البوت المعروض",
    "setMyDescription",
    "getMyDescription",
    "setMyShortDescription",
    "getMyShortDescription",
    "وصف البوت",
    "الوصف القصير للبوت",
    "setMyDefaultAdministratorRights",
    "getMyDefaultAdministratorRights",
    "صلاحيات المشرف الافتراضية",
    "setChatMenuButton",
    "getChatMenuButton",
    "زر قائمة الدردشة",
    "setMyProfilePhoto",
    "deleteMyProfilePhoto",
    "getMyName",
    "صورة البوت",
    "setWebhook",
    "deleteWebhook",
    "getWebhookInfo",
    "getUpdates",
    "ويبهوك تليجرام",
    "إلغاء ويبهوك",
    "sendMessage",
    "sendPhoto",
    "sendDocument",
    "forwardMessage",
    "copyMessage",
    "إرسال رسالة تليجرام",
    "إعادة توجيه رسالة",
    "editMessageText",
    "deleteMessage",
    "answerCallbackQuery",
    "editMessageReplyMarkup",
    "تعديل رسالة تليجرام",
    "حذف رسالة تليجرام",
    "رد على زر البوت",
    "sendPoll",
    "stopPoll",
    "sendDice",
    "sendLocation",
    "sendVenue",
    "sendContact",
    "استطلاع تليجرام",
    "إيقاف استطلاع البوت",
    "إرسال موقع تليجرام",
    "جهة اتصال البوت",
  ],
  alternates: { canonical: `${SITE}${PATH}` },
  openGraph: {
    title: "تفعيل بوت تليجرام — سوق تولز",
    description: "بوت يعمل على توكنك. طلب واحد = بوت واحد. لا سحب نقدي ولا كود للتحميل.",
    url: `${SITE}${PATH}`,
    locale: "ar_AR",
    type: "website",
    images: [{ url: `${SITE}/og/cover.jpg`, width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "تفعيل بوت تليجرام — سوق تولز",
    description: "منتج جاهز على توكنك. طلب واحد = بوت واحد. لا سحب نقدي.",
    images: [`${SITE}/og/cover.jpg`],
  },
};
