"""
Owner spec, 2026-09-12 ("علامة مائية حقيقية... بيانات وصفية حقيقية"):
real, pixel-level video post-processing (watermark burned into every
frame + narration + ownership metadata) — shared by every video SOURCE
this project has (Cloudflare's hosted model, and now a self-hosted
Hugging Face Space, see hf_video.py) so this logic exists exactly once.

Extracted out of cloudflare_ai.py (2026-09-12) once a second real video
source (hf_video.py) needed the exact same finishing steps — keeping it
duplicated a second time would have meant two copies to keep in sync
for a change that has nothing to do with which model generated the raw
pixels. Narration audio is still fetched from Cloudflare's hosted TTS
(cloudflare_ai.generate_speech) regardless of which model generated the
video itself — imported lazily inside finish_video() rather than at
module load time, since cloudflare_ai.py imports THIS module at the top
of its own file (a top-level circular import would break at process
start; a lazy one, resolved only when finish_video actually runs, does
not)."""
import logging
import os
import subprocess
import tempfile

logger = logging.getLogger("nova")

_WATERMARK_TEXT = "Nova AI"
# Owner report, 2026-09-12 (real screenshot on the ModelScope-generated
# image): a first attempt at these two alpha values read as an opaque
# label, not a watermark — kept in sync with cloudflare_ai.py's /
# modelscope-studio/app.py's own _add_watermark (box 90->45, text
# 200->130).
_WATERMARK_BOX_ALPHA = 45
_WATERMARK_TEXT_ALPHA = 130
_NARRATION_MAX_CHARS = 200


def finish_video(mp4_bytes: bytes, prompt: str) -> bytes:
    """Real per-frame watermark (ffmpeg's drawtext filter — burns the
    mark into every single frame's actual pixels, not a prompt
    instruction to the model) + real narration (Cloudflare TTS) + real
    MP4 metadata atoms (ffmpeg -metadata, the honest ID3-equivalent for
    MP4 — same reasoning as modelscope-studio/app.py's
    _add_video_ownership_metadata)."""
    import imageio_ffmpeg

    ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()
    with tempfile.TemporaryDirectory() as tmp:
        raw_path = os.path.join(tmp, "raw.mp4")
        watermarked_path = os.path.join(tmp, "watermarked.mp4")
        with open(raw_path, "wb") as f:
            f.write(mp4_bytes)

        # drawtext escaping: colon/backslash are the filter's own syntax
        # characters — "Nova AI" contains neither, so no escaping needed
        # for this fixed literal, unlike an arbitrary user-supplied string.
        drawtext = (
            f"drawtext=text='{_WATERMARK_TEXT}':fontcolor=white@{_WATERMARK_TEXT_ALPHA / 255:.2f}:"
            f"fontsize=h/24:box=1:boxcolor=black@{_WATERMARK_BOX_ALPHA / 255:.2f}:boxborderw=8:"
            "x=w-tw-16:y=h-th-16"
        )
        subprocess.run(
            [ffmpeg_exe, "-y", "-i", raw_path, "-vf", drawtext, "-c:a", "copy", watermarked_path],
            check=True, capture_output=True, timeout=60,
        )

        narrated_path = watermarked_path
        narration_bytes = None
        try:
            from app import cloudflare_ai
            narration_bytes = cloudflare_ai.generate_speech(prompt[:_NARRATION_MAX_CHARS])
        except Exception:
            logger.info("media-finish: narration fetch failed — delivering the silent (but still watermarked) video instead")
        if narration_bytes:
            audio_path = os.path.join(tmp, "narration.mp3")
            muxed_path = os.path.join(tmp, "narrated.mp4")
            with open(audio_path, "wb") as f:
                f.write(narration_bytes)
            try:
                subprocess.run(
                    [
                        ffmpeg_exe, "-y",
                        "-i", watermarked_path,
                        "-stream_loop", "-1", "-i", audio_path,
                        "-map", "0:v", "-map", "1:a",
                        "-c:v", "copy", "-c:a", "aac",
                        "-shortest",
                        muxed_path,
                    ],
                    check=True, capture_output=True, timeout=60,
                )
                narrated_path = muxed_path
            except Exception:
                logger.exception("media-finish: narration mux failed — delivering the silent (but still watermarked) video instead")

        tagged_path = os.path.join(tmp, "tagged.mp4")
        subprocess.run(
            [
                ffmpeg_exe, "-y",
                "-i", narrated_path,
                "-c", "copy",
                "-metadata", "author=Nova AI",
                "-metadata", "copyright=Generated by Nova AI",
                "-metadata", "comment=Generated by Nova AI",
                tagged_path,
            ],
            check=True, capture_output=True, timeout=30,
        )
        with open(tagged_path, "rb") as f:
            return f.read()
